---
# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.mycompany.example".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is !!!recommended.
groupName: acme.ndemeshchenko.net

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

# Specifies if the webhook should be started in hostNetwork mode.
#
# Required for use in some managed kubernetes clusters (such as AWS EKS) with custom
# CNI (such as calico, weave, etc), because control-plane managed by AWS cannot communicate
# with pods' IP CIDR and admission webhooks are not working
hostNetwork: true

image:
  repository: ndemeshchenko/cert-manager-webhook-dnsmadeasy
  tag: 0.0.3
  pullPolicy: IfNotPresent

features:
  apiPriorityAndFairness: false

nameOverride: ''

fullnameOverride: ''

service:
  type: ClusterIP
  port: 443

resources: {}
    # requests:
    #   cpu: 10m
    #   memory: 32Mi

nodeSelector:
  kubernetes.io/os: linux

tolerations: []


# expects input structure as per specification https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#affinity-v1-core
# for example:
#   affinity:
#     nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: foo.bar.com/role
#            operator: In
#            values:
#            - master
affinity: {}
