groupName: acme.ndemeshchenko.net
certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager
hostNetwork: true
image:
  repository: ndemeshchenko/cert-manager-webhook-dnsmadeasy
  tag: 0.0.4
  pullPolicy: IfNotPresent
features:
  apiPriorityAndFairness: false
nameOverride: ''
fullnameOverride: ''
service:
  type: ClusterIP
  port: 443
resources: {}
nodeSelector:
  kubernetes.io/os: linux
tolerations: []
affinity: {}
# RBAC configuration
rbac:
  # -- If pspEnabled true, a PodSecurityPolicy is created for K8s that use psp.
  pspEnabled: false