groupName: acme.ndemeshchenko.net
certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager
image:
  repository: ndemeshchenko/cert-manager-webhook-dnsmadeasy
  tag: 0.0.1
  pullPolicy: IfNotPresent
features:
  apiPriorityAndFairness: false
nameOverride: ''
fullnameOverride: ''
service:
  type: ClusterIP
  port: 443
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
